ethereum_rpc = "https://ethereum-hoodi-rpc.publicnode.com"
drosera_rpc = "https://relay.hoodi.drosera.io"
eth_chain_id = 560048
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

[traps]

[traps.vesting_cliff]
path = "out/VestingCliffTrap.sol/VestingCliffTrap.json"
response_contract = "0xREPLACE_WITH_CLIFFRESPONSE_ADDRESS"
response_function = "respondWithCliff(address,address,uint256,uint256,bool)"
cooldown_period_blocks = 50
min_number_of_operators = 1
max_number_of_operators = 2
block_sample_size = 1
private_trap = true
whitelist = ["YOUR_OPERATOR_ADDRESS"]
